---
title: "Lightening Round Essays"
format: html
editor: visual
---

**Answer each of the following questions with *one sentence* including a brief explanation.**

1.  Finish the sentence with another student’s name: "If \[Name of Student\] doesn’t earn an A, then nobody should, because..." Explain your choice and your reasoning.

    1.  If Fisher doesn't earn an A, then nobody should, because he's really smart.

2.  What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.

    1.  The most difficult part of the class for me was the statistical analyses at the very end. I was pretty lost in lab 10

3.  What was the easiest part of the class for you? Explain why.

    1.  The easiest part of the class for me was the data manipulation and joins and such since I am a computer science major and I just recently took a databases class.

4.  What part of the class surprised or interested you the most? Explain why.

    1.  Lab 5 interested me the most because the investigation element of it was really interesting and fun and I liked how it was open ended and you could implement your own solution to find the murderer.

5.  Give one piece of advice to a student just beginning a quarter of STAT 331 that will help them be successful in learning.

    1.  I would make sure to try to actually learn r and not just use chat gpt for everything
